/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var KeyWithIntegerValue_pb = require('./KeyWithIntegerValue_pb.js');
goog.exportSymbol('proto.NetworkAddressMappings', null, global);
goog.exportSymbol('proto.NetworkAddresses', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkAddresses = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.NetworkAddresses.repeatedFields_, null);
};
goog.inherits(proto.NetworkAddresses, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkAddresses.displayName = 'proto.NetworkAddresses';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.NetworkAddresses.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkAddresses.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkAddresses.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkAddresses} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkAddresses.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressesList: jspb.Message.getRepeatedField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkAddresses}
 */
proto.NetworkAddresses.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkAddresses;
  return proto.NetworkAddresses.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkAddresses} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkAddresses}
 */
proto.NetworkAddresses.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddresses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkAddresses.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkAddresses.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkAddresses} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkAddresses.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string addresses = 1;
 * @return {!Array.<string>}
 */
proto.NetworkAddresses.prototype.getAddressesList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array.<string>} value */
proto.NetworkAddresses.prototype.setAddressesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.NetworkAddresses.prototype.addAddresses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.NetworkAddresses.prototype.clearAddressesList = function() {
  this.setAddressesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkAddressMappings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.NetworkAddressMappings.repeatedFields_, null);
};
goog.inherits(proto.NetworkAddressMappings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkAddressMappings.displayName = 'proto.NetworkAddressMappings';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.NetworkAddressMappings.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkAddressMappings.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkAddressMappings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkAddressMappings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkAddressMappings.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressidsList: jspb.Message.toObjectList(msg.getAddressidsList(),
    KeyWithIntegerValue_pb.KeyWithIntegerValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkAddressMappings}
 */
proto.NetworkAddressMappings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkAddressMappings;
  return proto.NetworkAddressMappings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkAddressMappings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkAddressMappings}
 */
proto.NetworkAddressMappings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new KeyWithIntegerValue_pb.KeyWithIntegerValue;
      reader.readMessage(value,KeyWithIntegerValue_pb.KeyWithIntegerValue.deserializeBinaryFromReader);
      msg.addAddressids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkAddressMappings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkAddressMappings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkAddressMappings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkAddressMappings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      KeyWithIntegerValue_pb.KeyWithIntegerValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated KeyWithIntegerValue addressIds = 1;
 * @return {!Array.<!proto.KeyWithIntegerValue>}
 */
proto.NetworkAddressMappings.prototype.getAddressidsList = function() {
  return /** @type{!Array.<!proto.KeyWithIntegerValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, KeyWithIntegerValue_pb.KeyWithIntegerValue, 1));
};


/** @param {!Array.<!proto.KeyWithIntegerValue>} value */
proto.NetworkAddressMappings.prototype.setAddressidsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.KeyWithIntegerValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.KeyWithIntegerValue}
 */
proto.NetworkAddressMappings.prototype.addAddressids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.KeyWithIntegerValue, opt_index);
};


proto.NetworkAddressMappings.prototype.clearAddressidsList = function() {
  this.setAddressidsList([]);
};


goog.object.extend(exports, proto);
