/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Common_pb = require('./Common_pb.js');
var Downstream_pb = require('./Downstream_pb.js');
var KeyWithStringValue_pb = require('./KeyWithStringValue_pb.js');
goog.exportSymbol('proto.LogMessage', null, global);
goog.exportSymbol('proto.RefType', null, global);
goog.exportSymbol('proto.SpanLayer', null, global);
goog.exportSymbol('proto.SpanObject', null, global);
goog.exportSymbol('proto.TraceSegmentObject', null, global);
goog.exportSymbol('proto.TraceSegmentReference', null, global);
goog.exportSymbol('proto.UniqueId', null, global);
goog.exportSymbol('proto.UpstreamSegment', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UpstreamSegment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.UpstreamSegment.repeatedFields_, null);
};
goog.inherits(proto.UpstreamSegment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.UpstreamSegment.displayName = 'proto.UpstreamSegment';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.UpstreamSegment.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UpstreamSegment.prototype.toObject = function(opt_includeInstance) {
  return proto.UpstreamSegment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UpstreamSegment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpstreamSegment.toObject = function(includeInstance, msg) {
  var f, obj = {
    globaltraceidsList: jspb.Message.toObjectList(msg.getGlobaltraceidsList(),
    proto.UniqueId.toObject, includeInstance),
    segment: msg.getSegment_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UpstreamSegment}
 */
proto.UpstreamSegment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UpstreamSegment;
  return proto.UpstreamSegment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UpstreamSegment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UpstreamSegment}
 */
proto.UpstreamSegment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UniqueId;
      reader.readMessage(value,proto.UniqueId.deserializeBinaryFromReader);
      msg.addGlobaltraceids(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSegment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UpstreamSegment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UpstreamSegment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UpstreamSegment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpstreamSegment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGlobaltraceidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.UniqueId.serializeBinaryToWriter
    );
  }
  f = message.getSegment_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * repeated UniqueId globalTraceIds = 1;
 * @return {!Array.<!proto.UniqueId>}
 */
proto.UpstreamSegment.prototype.getGlobaltraceidsList = function() {
  return /** @type{!Array.<!proto.UniqueId>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.UniqueId, 1));
};


/** @param {!Array.<!proto.UniqueId>} value */
proto.UpstreamSegment.prototype.setGlobaltraceidsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.UniqueId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.UniqueId}
 */
proto.UpstreamSegment.prototype.addGlobaltraceids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.UniqueId, opt_index);
};


proto.UpstreamSegment.prototype.clearGlobaltraceidsList = function() {
  this.setGlobaltraceidsList([]);
};


/**
 * optional bytes segment = 2;
 * @return {!(string|Uint8Array)}
 */
proto.UpstreamSegment.prototype.getSegment = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes segment = 2;
 * This is a type-conversion wrapper around `getSegment()`
 * @return {string}
 */
proto.UpstreamSegment.prototype.getSegment_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSegment()));
};


/**
 * optional bytes segment = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSegment()`
 * @return {!Uint8Array}
 */
proto.UpstreamSegment.prototype.getSegment_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSegment()));
};


/** @param {!(string|Uint8Array)} value */
proto.UpstreamSegment.prototype.setSegment = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UniqueId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.UniqueId.repeatedFields_, null);
};
goog.inherits(proto.UniqueId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.UniqueId.displayName = 'proto.UniqueId';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.UniqueId.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UniqueId.prototype.toObject = function(opt_includeInstance) {
  return proto.UniqueId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UniqueId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UniqueId.toObject = function(includeInstance, msg) {
  var f, obj = {
    idpartsList: jspb.Message.getRepeatedField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UniqueId}
 */
proto.UniqueId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UniqueId;
  return proto.UniqueId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UniqueId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UniqueId}
 */
proto.UniqueId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array.<number>} */ (reader.readPackedInt64());
      msg.setIdpartsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UniqueId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UniqueId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UniqueId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UniqueId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdpartsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      1,
      f
    );
  }
};


/**
 * repeated int64 idParts = 1;
 * @return {!Array.<number>}
 */
proto.UniqueId.prototype.getIdpartsList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array.<number>} value */
proto.UniqueId.prototype.setIdpartsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.UniqueId.prototype.addIdparts = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.UniqueId.prototype.clearIdpartsList = function() {
  this.setIdpartsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TraceSegmentObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TraceSegmentObject.repeatedFields_, null);
};
goog.inherits(proto.TraceSegmentObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TraceSegmentObject.displayName = 'proto.TraceSegmentObject';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TraceSegmentObject.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TraceSegmentObject.prototype.toObject = function(opt_includeInstance) {
  return proto.TraceSegmentObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TraceSegmentObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TraceSegmentObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    tracesegmentid: (f = msg.getTracesegmentid()) && proto.UniqueId.toObject(includeInstance, f),
    spansList: jspb.Message.toObjectList(msg.getSpansList(),
    proto.SpanObject.toObject, includeInstance),
    applicationid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    applicationinstanceid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    issizelimited: jspb.Message.getFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TraceSegmentObject}
 */
proto.TraceSegmentObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TraceSegmentObject;
  return proto.TraceSegmentObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TraceSegmentObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TraceSegmentObject}
 */
proto.TraceSegmentObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UniqueId;
      reader.readMessage(value,proto.UniqueId.deserializeBinaryFromReader);
      msg.setTracesegmentid(value);
      break;
    case 2:
      var value = new proto.SpanObject;
      reader.readMessage(value,proto.SpanObject.deserializeBinaryFromReader);
      msg.addSpans(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setApplicationid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setApplicationinstanceid(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIssizelimited(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TraceSegmentObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TraceSegmentObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TraceSegmentObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TraceSegmentObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTracesegmentid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.UniqueId.serializeBinaryToWriter
    );
  }
  f = message.getSpansList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SpanObject.serializeBinaryToWriter
    );
  }
  f = message.getApplicationid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getApplicationinstanceid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getIssizelimited();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional UniqueId traceSegmentId = 1;
 * @return {?proto.UniqueId}
 */
proto.TraceSegmentObject.prototype.getTracesegmentid = function() {
  return /** @type{?proto.UniqueId} */ (
    jspb.Message.getWrapperField(this, proto.UniqueId, 1));
};


/** @param {?proto.UniqueId|undefined} value */
proto.TraceSegmentObject.prototype.setTracesegmentid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.TraceSegmentObject.prototype.clearTracesegmentid = function() {
  this.setTracesegmentid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.TraceSegmentObject.prototype.hasTracesegmentid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated SpanObject spans = 2;
 * @return {!Array.<!proto.SpanObject>}
 */
proto.TraceSegmentObject.prototype.getSpansList = function() {
  return /** @type{!Array.<!proto.SpanObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SpanObject, 2));
};


/** @param {!Array.<!proto.SpanObject>} value */
proto.TraceSegmentObject.prototype.setSpansList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SpanObject=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SpanObject}
 */
proto.TraceSegmentObject.prototype.addSpans = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SpanObject, opt_index);
};


proto.TraceSegmentObject.prototype.clearSpansList = function() {
  this.setSpansList([]);
};


/**
 * optional int32 applicationId = 3;
 * @return {number}
 */
proto.TraceSegmentObject.prototype.getApplicationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.TraceSegmentObject.prototype.setApplicationid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 applicationInstanceId = 4;
 * @return {number}
 */
proto.TraceSegmentObject.prototype.getApplicationinstanceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.TraceSegmentObject.prototype.setApplicationinstanceid = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional bool isSizeLimited = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.TraceSegmentObject.prototype.getIssizelimited = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.TraceSegmentObject.prototype.setIssizelimited = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TraceSegmentReference = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TraceSegmentReference, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TraceSegmentReference.displayName = 'proto.TraceSegmentReference';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TraceSegmentReference.prototype.toObject = function(opt_includeInstance) {
  return proto.TraceSegmentReference.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TraceSegmentReference} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TraceSegmentReference.toObject = function(includeInstance, msg) {
  var f, obj = {
    reftype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    parenttracesegmentid: (f = msg.getParenttracesegmentid()) && proto.UniqueId.toObject(includeInstance, f),
    parentspanid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    parentapplicationinstanceid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    networkaddress: jspb.Message.getFieldWithDefault(msg, 5, ""),
    networkaddressid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    entryapplicationinstanceid: jspb.Message.getFieldWithDefault(msg, 7, 0),
    entryservicename: jspb.Message.getFieldWithDefault(msg, 8, ""),
    entryserviceid: jspb.Message.getFieldWithDefault(msg, 9, 0),
    parentservicename: jspb.Message.getFieldWithDefault(msg, 10, ""),
    parentserviceid: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TraceSegmentReference}
 */
proto.TraceSegmentReference.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TraceSegmentReference;
  return proto.TraceSegmentReference.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TraceSegmentReference} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TraceSegmentReference}
 */
proto.TraceSegmentReference.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.RefType} */ (reader.readEnum());
      msg.setReftype(value);
      break;
    case 2:
      var value = new proto.UniqueId;
      reader.readMessage(value,proto.UniqueId.deserializeBinaryFromReader);
      msg.setParenttracesegmentid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setParentspanid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setParentapplicationinstanceid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkaddress(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNetworkaddressid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEntryapplicationinstanceid(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntryservicename(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEntryserviceid(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentservicename(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setParentserviceid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TraceSegmentReference.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TraceSegmentReference.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TraceSegmentReference} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TraceSegmentReference.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReftype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getParenttracesegmentid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.UniqueId.serializeBinaryToWriter
    );
  }
  f = message.getParentspanid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getParentapplicationinstanceid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getNetworkaddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNetworkaddressid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getEntryapplicationinstanceid();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getEntryservicename();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEntryserviceid();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getParentservicename();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getParentserviceid();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
};


/**
 * optional RefType refType = 1;
 * @return {!proto.RefType}
 */
proto.TraceSegmentReference.prototype.getReftype = function() {
  return /** @type {!proto.RefType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.RefType} value */
proto.TraceSegmentReference.prototype.setReftype = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional UniqueId parentTraceSegmentId = 2;
 * @return {?proto.UniqueId}
 */
proto.TraceSegmentReference.prototype.getParenttracesegmentid = function() {
  return /** @type{?proto.UniqueId} */ (
    jspb.Message.getWrapperField(this, proto.UniqueId, 2));
};


/** @param {?proto.UniqueId|undefined} value */
proto.TraceSegmentReference.prototype.setParenttracesegmentid = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.TraceSegmentReference.prototype.clearParenttracesegmentid = function() {
  this.setParenttracesegmentid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.TraceSegmentReference.prototype.hasParenttracesegmentid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 parentSpanId = 3;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getParentspanid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setParentspanid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 parentApplicationInstanceId = 4;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getParentapplicationinstanceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setParentapplicationinstanceid = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string networkAddress = 5;
 * @return {string}
 */
proto.TraceSegmentReference.prototype.getNetworkaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.TraceSegmentReference.prototype.setNetworkaddress = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional int32 networkAddressId = 6;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getNetworkaddressid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setNetworkaddressid = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional int32 entryApplicationInstanceId = 7;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getEntryapplicationinstanceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setEntryapplicationinstanceid = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string entryServiceName = 8;
 * @return {string}
 */
proto.TraceSegmentReference.prototype.getEntryservicename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.TraceSegmentReference.prototype.setEntryservicename = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional int32 entryServiceId = 9;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getEntryserviceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setEntryserviceid = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string parentServiceName = 10;
 * @return {string}
 */
proto.TraceSegmentReference.prototype.getParentservicename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.TraceSegmentReference.prototype.setParentservicename = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional int32 parentServiceId = 11;
 * @return {number}
 */
proto.TraceSegmentReference.prototype.getParentserviceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.TraceSegmentReference.prototype.setParentserviceid = function(value) {
  jspb.Message.setField(this, 11, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SpanObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SpanObject.repeatedFields_, null);
};
goog.inherits(proto.SpanObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SpanObject.displayName = 'proto.SpanObject';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SpanObject.repeatedFields_ = [5,15,16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SpanObject.prototype.toObject = function(opt_includeInstance) {
  return proto.SpanObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SpanObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SpanObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    spanid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    parentspanid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    starttime: jspb.Message.getFieldWithDefault(msg, 3, 0),
    endtime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    refsList: jspb.Message.toObjectList(msg.getRefsList(),
    proto.TraceSegmentReference.toObject, includeInstance),
    operationnameid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    operationname: jspb.Message.getFieldWithDefault(msg, 7, ""),
    peerid: jspb.Message.getFieldWithDefault(msg, 8, 0),
    peer: jspb.Message.getFieldWithDefault(msg, 9, ""),
    spantype: jspb.Message.getFieldWithDefault(msg, 10, 0),
    spanlayer: jspb.Message.getFieldWithDefault(msg, 11, 0),
    componentid: jspb.Message.getFieldWithDefault(msg, 12, 0),
    component: jspb.Message.getFieldWithDefault(msg, 13, ""),
    iserror: jspb.Message.getFieldWithDefault(msg, 14, false),
    tagsList: jspb.Message.toObjectList(msg.getTagsList(),
    KeyWithStringValue_pb.KeyWithStringValue.toObject, includeInstance),
    logsList: jspb.Message.toObjectList(msg.getLogsList(),
    proto.LogMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SpanObject}
 */
proto.SpanObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SpanObject;
  return proto.SpanObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SpanObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SpanObject}
 */
proto.SpanObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpanid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setParentspanid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndtime(value);
      break;
    case 5:
      var value = new proto.TraceSegmentReference;
      reader.readMessage(value,proto.TraceSegmentReference.deserializeBinaryFromReader);
      msg.addRefs(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOperationnameid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperationname(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeerid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPeer(value);
      break;
    case 10:
      var value = /** @type {!proto.SpanType} */ (reader.readEnum());
      msg.setSpantype(value);
      break;
    case 11:
      var value = /** @type {!proto.SpanLayer} */ (reader.readEnum());
      msg.setSpanlayer(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setComponentid(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setComponent(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIserror(value);
      break;
    case 15:
      var value = new KeyWithStringValue_pb.KeyWithStringValue;
      reader.readMessage(value,KeyWithStringValue_pb.KeyWithStringValue.deserializeBinaryFromReader);
      msg.addTags(value);
      break;
    case 16:
      var value = new proto.LogMessage;
      reader.readMessage(value,proto.LogMessage.deserializeBinaryFromReader);
      msg.addLogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SpanObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SpanObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SpanObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SpanObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpanid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getParentspanid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getStarttime();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getEndtime();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getRefsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.TraceSegmentReference.serializeBinaryToWriter
    );
  }
  f = message.getOperationnameid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getOperationname();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPeerid();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getPeer();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSpantype();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getSpanlayer();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getComponentid();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getComponent();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getIserror();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      KeyWithStringValue_pb.KeyWithStringValue.serializeBinaryToWriter
    );
  }
  f = message.getLogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      proto.LogMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 spanId = 1;
 * @return {number}
 */
proto.SpanObject.prototype.getSpanid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setSpanid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 parentSpanId = 2;
 * @return {number}
 */
proto.SpanObject.prototype.getParentspanid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setParentspanid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int64 startTime = 3;
 * @return {number}
 */
proto.SpanObject.prototype.getStarttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setStarttime = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int64 endTime = 4;
 * @return {number}
 */
proto.SpanObject.prototype.getEndtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setEndtime = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * repeated TraceSegmentReference refs = 5;
 * @return {!Array.<!proto.TraceSegmentReference>}
 */
proto.SpanObject.prototype.getRefsList = function() {
  return /** @type{!Array.<!proto.TraceSegmentReference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TraceSegmentReference, 5));
};


/** @param {!Array.<!proto.TraceSegmentReference>} value */
proto.SpanObject.prototype.setRefsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.TraceSegmentReference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TraceSegmentReference}
 */
proto.SpanObject.prototype.addRefs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.TraceSegmentReference, opt_index);
};


proto.SpanObject.prototype.clearRefsList = function() {
  this.setRefsList([]);
};


/**
 * optional int32 operationNameId = 6;
 * @return {number}
 */
proto.SpanObject.prototype.getOperationnameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setOperationnameid = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string operationName = 7;
 * @return {string}
 */
proto.SpanObject.prototype.getOperationname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.SpanObject.prototype.setOperationname = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional int32 peerId = 8;
 * @return {number}
 */
proto.SpanObject.prototype.getPeerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setPeerid = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional string peer = 9;
 * @return {string}
 */
proto.SpanObject.prototype.getPeer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.SpanObject.prototype.setPeer = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional SpanType spanType = 10;
 * @return {!proto.SpanType}
 */
proto.SpanObject.prototype.getSpantype = function() {
  return /** @type {!proto.SpanType} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {!proto.SpanType} value */
proto.SpanObject.prototype.setSpantype = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional SpanLayer spanLayer = 11;
 * @return {!proto.SpanLayer}
 */
proto.SpanObject.prototype.getSpanlayer = function() {
  return /** @type {!proto.SpanLayer} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {!proto.SpanLayer} value */
proto.SpanObject.prototype.setSpanlayer = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional int32 componentId = 12;
 * @return {number}
 */
proto.SpanObject.prototype.getComponentid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.SpanObject.prototype.setComponentid = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional string component = 13;
 * @return {string}
 */
proto.SpanObject.prototype.getComponent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.SpanObject.prototype.setComponent = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional bool isError = 14;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.SpanObject.prototype.getIserror = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 14, false));
};


/** @param {boolean} value */
proto.SpanObject.prototype.setIserror = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * repeated KeyWithStringValue tags = 15;
 * @return {!Array.<!proto.KeyWithStringValue>}
 */
proto.SpanObject.prototype.getTagsList = function() {
  return /** @type{!Array.<!proto.KeyWithStringValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, KeyWithStringValue_pb.KeyWithStringValue, 15));
};


/** @param {!Array.<!proto.KeyWithStringValue>} value */
proto.SpanObject.prototype.setTagsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.KeyWithStringValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.KeyWithStringValue}
 */
proto.SpanObject.prototype.addTags = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.KeyWithStringValue, opt_index);
};


proto.SpanObject.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


/**
 * repeated LogMessage logs = 16;
 * @return {!Array.<!proto.LogMessage>}
 */
proto.SpanObject.prototype.getLogsList = function() {
  return /** @type{!Array.<!proto.LogMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.LogMessage, 16));
};


/** @param {!Array.<!proto.LogMessage>} value */
proto.SpanObject.prototype.setLogsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.LogMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.LogMessage}
 */
proto.SpanObject.prototype.addLogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.LogMessage, opt_index);
};


proto.SpanObject.prototype.clearLogsList = function() {
  this.setLogsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LogMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.LogMessage.repeatedFields_, null);
};
goog.inherits(proto.LogMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.LogMessage.displayName = 'proto.LogMessage';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LogMessage.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LogMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.LogMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LogMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LogMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    time: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    KeyWithStringValue_pb.KeyWithStringValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LogMessage}
 */
proto.LogMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LogMessage;
  return proto.LogMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LogMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LogMessage}
 */
proto.LogMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTime(value);
      break;
    case 2:
      var value = new KeyWithStringValue_pb.KeyWithStringValue;
      reader.readMessage(value,KeyWithStringValue_pb.KeyWithStringValue.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LogMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LogMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LogMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LogMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTime();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      KeyWithStringValue_pb.KeyWithStringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 time = 1;
 * @return {number}
 */
proto.LogMessage.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.LogMessage.prototype.setTime = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated KeyWithStringValue data = 2;
 * @return {!Array.<!proto.KeyWithStringValue>}
 */
proto.LogMessage.prototype.getDataList = function() {
  return /** @type{!Array.<!proto.KeyWithStringValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, KeyWithStringValue_pb.KeyWithStringValue, 2));
};


/** @param {!Array.<!proto.KeyWithStringValue>} value */
proto.LogMessage.prototype.setDataList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.KeyWithStringValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.KeyWithStringValue}
 */
proto.LogMessage.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.KeyWithStringValue, opt_index);
};


proto.LogMessage.prototype.clearDataList = function() {
  this.setDataList([]);
};


/**
 * @enum {number}
 */
proto.RefType = {
  CROSSPROCESS: 0,
  CROSSTHREAD: 1
};

/**
 * @enum {number}
 */
proto.SpanLayer = {
  UNKNOWN: 0,
  DATABASE: 1,
  RPCFRAMEWORK: 2,
  HTTP: 3,
  MQ: 4,
  CACHE: 5
};

goog.object.extend(exports, proto);
